# This is a dummy makefile that will get used to build this "extension" when
# the pre-built protoc will work on the system
# This file will get overwritten by extconf.rb if it needs to build protoc
# from source

build:

install:
